services:
  runner:
    image: ruby:3.0
    working_dir: /work
    init: true
    entrypoint: ['/work/sample-ci/docker/runner/entrypoint.sh']
    env_file: .env
    environment:
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - SERVER_URL=${SERVER_URL:-http://web:4242}
      - BUNDLE_JOBS=5
    volumes:
      - work:/work
      - gem:/usr/local/bundle

  stripe:
    image: stripe/stripe-cli:v1.5.3
    init: true
    entrypoint: ['/bin/ash']
    command: ['-c', '/bin/stripe --api-key=$STRIPE_SECRET_KEY listen --forward-to http://web:4242/webhook']
    env_file: .env
    environment:
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}

  web:
    image: "ruby:latest"
    working_dir: /work/custom-payment-flow/server/ruby
    init: true
    entrypoint: ['/work/sample-ci/docker/ruby/entrypoint.sh']
    ports: ['4242:4242']
    env_file: .env
    environment:
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STATIC_DIR=../../client/html
    volumes:
      - work:/work

volumes:
  work:
  gem:
