services:
  runner:
    entrypoint: ['/work/.devcontainer/runner-entrypoint.sh']
    env_file: ../.env
    volumes:
      - ../..:/work
      - ../.ssh:/root/.ssh

  stripe:
    env_file: ../.env

  web:
    entrypoint: ""
    command: ['tail', '-f', '/dev/null']
    env_file: ../.env
    volumes:
      - ../..:/work
      - ../.ssh:/root/.ssh
