services:
  runner:
    image: ruby:3.0
    working_dir: /work
    init: true
    entrypoint: ['/work/sample-ci/docker/runner/entrypoint.sh']
    env_file: .env
    environment:
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - SERVER_URL=${SERVER_URL:-http://web:4242}
      - BUNDLE_JOBS=5
    volumes:
      - work:/work
      - gem:/usr/local/bundle

  stripe:
    image: stripe/stripe-cli:v1.5.3
    init: true
    entrypoint: ['/bin/ash']
    command: ['-c', '/bin/stripe --api-key=$STRIPE_SECRET_KEY listen --forward-to http://web:4242/webhook']
    env_file: .env
    environment:
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}

  web:
    image: "node:lts"
    working_dir: /work/custom-payment-flow/server/node
    init: true
    entrypoint: ['/work/sample-ci/docker/node/entrypoint.sh']
    ports: ['4242:4242']
    env_file: .env
    environment:
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STATIC_DIR=../../client/react-cra
    volumes:
      - work:/work

  frontend:
    profiles: ['frontend']
    build:
      context: .
      dockerfile: sample-ci/docker/react-cra/Dockerfile
    stdin_open: true
    working_dir: /work/custom-payment-flow/client/react-cra
    init: true
    entrypoint: ['/work/sample-ci/docker/react-cra/entrypoint.sh']
    ports: ['3000:3000']
    environment:
      - HOST=0.0.0.0
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      - SERVER_URL=${SERVER_URL:-http://web:4242}
    volumes:
      - work:/work

  selenium:
    profiles: ['e2e', 'frontend']
    image: selenium/standalone-chrome-debug:3.141
    ports: ['5900:5900', '4444:4444']
    environment:
      - VNC_NO_PASSWORD='1'

volumes:
  work:
  gem:
