name: Dependabot auto-merge
on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches:
      - 'dependabot/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: open

      - name: Enable auto-merge
        if: ${{ steps.findPr.outputs.pr }}
        run: gh pr merge --auto --merge "${{ steps.findPr.outputs.pr }}"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
