name: Dependabot auto-merge
on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches:
      - 'dependabot/**'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v1

      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: open
          sha: ${{ github.event.workflow_run }}

      - run: echo "Your PR is ${PR}"
        if: success() && steps.findPr.outputs.number
        env:
          PR: ${{ steps.findPr.outputs.pr }}

      - name: Enable auto-merge
        if: success() && steps.findPr.outputs.number
        run: gh pr merge --auto --merge "${{ steps.findPr.outputs.pr }}"
